name: DotNET

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-latest]
      fail-fast: false
      max-parallel: 4
    name: Test .net ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Set up environment
        run: ./bootstrap.cmd
      - name: Test with .Net
        run: ./build.cmd all
