name: SonarCloud

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository_owner == 'waffle'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - name: Analyze with SonarCloud
        run: ./mvnw verify sonar:sonar -B -D"license.skip=true" -D"sonar.projectKey=Waffle_waffle" -D"sonar.organization=waffle" -D"sonar.host.url=https://sonarcloud.io" -D"sonar.login=$SONAR_TOKEN"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
